# Generated by Django 4.2.29 on 2026-04-16 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('connection_type', models.CharField(choices=[('sql', 'SQL Database'), ('api', 'REST API'), ('graphql', 'GraphQL API')], max_length=20)),
                ('config', models.JSONField(help_text='Connection configuration (host, port, API key, etc.)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('layout', models.JSONField(default=dict, help_text='Grid layout configuration')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('filters', models.JSONField(default=list, help_text='Global dashboard filters')),
                ('is_public', models.BooleanField(default=False)),
                ('share_token', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('auto_refresh', models.BooleanField(default=False)),
                ('auto_refresh_interval', models.IntegerField(default=60, help_text='Seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('csv', 'CSV File'), ('excel', 'Excel File'), ('api', 'API Endpoint'), ('sql', 'SQL Database'), ('json', 'JSON File')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='datasets/')),
                ('query', models.TextField(blank=True, help_text='SQL query or API endpoint path')),
                ('schema', models.JSONField(default=dict, help_text='Column names and types')),
                ('row_count', models.IntegerField(default=0)),
                ('cached_data', models.JSONField(blank=True, default=list)),
                ('last_refreshed', models.DateTimeField(blank=True, null=True)),
                ('refresh_interval', models.IntegerField(default=3600, help_text='Refresh interval in seconds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.apiconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('widget_type', models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('table', 'Data Table'), ('kpi', 'KPI Card'), ('metric', 'Metric Card'), ('heatmap', 'Heatmap'), ('scatter', 'Scatter Plot')], max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Chart-specific config (axes, colors, etc.)')),
                ('query', models.TextField(blank=True, help_text='SQL query or transformation')),
                ('x_axis', models.CharField(blank=True, max_length=255)),
                ('y_axis', models.CharField(blank=True, max_length=255)),
                ('group_by', models.CharField(blank=True, max_length=255)),
                ('filters', models.JSONField(blank=True, default=list)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=4)),
                ('height', models.IntegerField(default=3)),
                ('background_color', models.CharField(default='#ffffff', max_length=10)),
                ('title_color', models.CharField(default='#000000', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='api.dashboard')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='api.dataset')),
            ],
            options={
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('auto_logout', models.IntegerField(default=3600, help_text='Seconds of inactivity before logout')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DashboardFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filter_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select'), ('multi_select', 'Multi-Select')], max_length=20)),
                ('column', models.CharField(help_text='Column to filter on', max_length=255)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, help_text='For select/multi_select', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_widgets', models.ManyToManyField(blank=True, related_name='applied_filters', to='api.widget')),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_filters', to='api.dashboard')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
